Fix Unix Timestamp
dedis/student20_pop pull request #181
Opened 2021-01-11 22:06 UTC by celinecamacho

Replace `java.util.Date` with `java.time.Instant` for the computation of Unix Timestamp in order to avoid issues with milliseconds.

2021-01-11 22:18 UTC, GabrielFleischer requested changes
You should pull the schema submodule. Right now it is downgraded

2021-01-12 08:00 UTC, jbmichel14 commented on app/src/main/java/com/github/dedis/student20_pop/utility/security/Hash.java
> +            if (elem == null) {
What if elem is not null but empty?

2021-01-12 08:01 UTC, jbmichel14 approved these changes

2021-01-12 09:50 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/utility/security/Hash.java
> +            if (elem == null) {
But `elem` is not always a String

2021-01-12 10:01 UTC, AlexisTabin approved these changes

2021-01-12 11:30 UTC, GabrielFleischer approved these changes

2021-01-12 11:31 UTC, merged