Improve software quality of package model
dedis/student20_pop pull request #183
Opened 2021-01-12 12:47 UTC by celinecamacho

Refactor, comment and test all classes in the package model. 

Packages inside model:
- [ ] event
- [ ] network.level.high
- [ ] network.level.low
- [ ] network.level.mid

2021-01-12 19:11 UTC, GabrielFleischer requested changes
Bugs were created in with Gson as the fields were changed in 
StateLao
UpdateLao
CreateMeeting
StateMeeting
WitnessMessage

@SerlializeName() msut be added

2021-01-12 19:11 UTC, GabrielFleischer commented on app/src/main/java/com/github/dedis/student20_pop/model/network/method/message/data/lao/StateLao.java
> +    private final long lastModified;
Problem, gson uses the field name to get the json property name.
So we need to add @SerializeName("last_modified")

2021-01-12 19:11 UTC, GabrielFleischer commented on app/src/main/java/com/github/dedis/student20_pop/model/network/method/message/data/lao/StateLao.java
>      public long getLast_modified() {
Change this name

2021-01-12 19:11 UTC, GabrielFleischer commented on app/src/main/java/com/github/dedis/student20_pop/model/network/method/message/data/lao/UpdateLao.java
> +    private final long lastModified;
Same as StateLao

2021-01-12 19:11 UTC, GabrielFleischer commented on app/src/main/java/com/github/dedis/student20_pop/model/network/method/message/data/meeting/CreateMeeting.java
> +    private final long lastModified;
Same as StateLao

2021-01-12 19:11 UTC, GabrielFleischer commented on app/src/main/java/com/github/dedis/student20_pop/model/network/method/message/data/meeting/StateMeeting.java
> +    private final long lastModified;
Same as state lao

2021-01-12 19:11 UTC, GabrielFleischer commented on app/src/main/java/com/github/dedis/student20_pop/model/network/method/message/data/message/WitnessMessage.java
> +    private final String messageId;
Same as state lao

2021-01-12 19:11 UTC, GabrielFleischer commented on app/src/main/java/com/github/dedis/student20_pop/model/network/method/message/data/lao/StateLao.java
> +    private final long lastModified;
This name should not be changed. It is used by Gson to compute the json property name,
You need to add @SerializeName("last_modified")

2021-01-12 19:11 UTC, GabrielFleischer commented on app/src/main/java/com/github/dedis/student20_pop/model/network/method/message/data/lao/StateLao.java
>      public long getLast_modified() {
Change this to fit the name

2021-01-12 19:16 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/model/event/Event.java
> +    private ObservableArrayList<String> attendees;
Indeed, i'm going to change that

2021-01-13 11:09 UTC, GabrielFleischer approved these changes

2021-01-13 12:00 UTC, jbmichel14 approved these changes

2021-01-13 12:41 UTC, AlexisTabin approved these changes

2021-01-13 13:05 UTC, merged