QRCode scanner
dedis/student20_pop pull request #25
Opened 2020-10-19 21:02 UTC by GabrielFleischer

Add a qrcode scanner to the connect ui

2020-10-19 21:20 UTC, haoqianzhang approved these changes

2020-10-20 07:20 UTC, celinecamacho reviewed
Great job, just a few comments on values that should be stored in res/values

2020-10-20 07:20 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/qrcode/CameraPreview.java
> +        int width = 240;
Could you store this values in res/values/dimens.xml?

2020-10-20 07:20 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/ui/ConnectFragment.java
> +                .setRequestedPreviewSize(1600, 1024)
Same comment for these values: 1600, 1024 and 15.0f

2020-10-20 07:20 UTC, celinecamacho commented on app/src/main/res/layout/fragment_connect.xml
> +            android:layout_margin="50dp">
Same comment for the values in line 37, 42 and 44

2020-10-20 07:20 UTC, celinecamacho commented on app/src/main/res/layout/fragment_connect.xml
> +                android:background="#03A9F4"
You can store the colors in the file res/values/colors.xml and then access them using @colors/id

2020-10-20 07:20 UTC, celinecamacho commented on app/src/main/res/values/strings.xml
>      <string name="text_temp_connect">Connect UI</string>
You can delete the two strings "text_temp_connect" and "text_temp_launch" if you're not using them anymore

2020-10-20 07:25 UTC, celinecamacho approved these changes

2020-10-20 09:40 UTC, lhmerino requested changes

2020-10-20 09:40 UTC, lhmerino commented on app/src/main/java/com/github/dedis/student20_pop/qrcode/CameraPreview.java
> +public class CameraPreview extends ViewGroup {
Please add a comment to discuss what is the purpose of this class

2020-10-20 09:40 UTC, lhmerino commented on app/src/main/java/com/github/dedis/student20_pop/qrcode/QRFocusingProcessor.java
> +public class QRFocusingProcessor extends FocusingProcessor<Barcode> {
Comment on this class too

2020-10-20 09:40 UTC, lhmerino commented on app/src/androidTest/java/com/github/dedis/student20_pop/ui/ConnectFragmentTest.java
> +public class ConnectFragmentTest {
Please add comment here as well

2020-10-20 09:41 UTC, lhmerino commented
Looks great, thank you! Just would like to see more comments to understand the purpose of each class at a quick glance.

2020-10-20 10:21 UTC, lhmerino approved these changes

2020-10-20 10:40 UTC, merged