Implement keys model
dedis/student20_pop pull request #44
Opened 2020-10-26 19:14 UTC by jbmichel14

2020-10-27 17:15 UTC, lhmerino approved these changes
Looks good! it's great that you have been able to create identities (private-public keys)

2020-10-28 12:42 UTC, celinecamacho requested changes
Great, just need to modify some tests in PersonTest

2020-10-28 12:42 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/model/Keys.java
> -        this.privateKey = "";
You should modify PersonTest because the class Person uses getPublicKey() and getPrivateKey()

2020-10-29 11:04 UTC, celinecamacho approved these changes

2020-10-29 11:06 UTC, merged