Implement attendee UI
dedis/student20_pop pull request #50
Opened 2020-10-29 17:47 UTC by jbmichel14

To test the attendee UI, the boolean in MainActivity has to be set to true.

2020-10-29 18:57 UTC, AlexisTabin approved these changes

2020-10-29 18:57 UTC, AlexisTabin commented on app/src/androidTest/java/com/github/dedis/student20_pop/ui/ConnectFragmentTest.java
> +
useless line

2020-11-08 19:57 UTC, celinecamacho requested changes
Good job! There's just a method in MainActivity that could be useful to have and some comments left hanging

2020-11-08 19:57 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/ui/AttendeeFragment.java
> +//How do we pass the info from Connect UI to Attendee UI ?
Are these comments relevant?

2020-11-08 19:57 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/ui/AttendeeFragment.java
> +        //((TextView) properties.findViewById(R.id.witness_list)).setText(lao.getWitnesses().toString());
Is this comment important?

2020-11-08 19:57 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/utility/attendeeUI/ExpandableListViewEventAdapter.java
> +        return childPosition; //((Event) getChild(groupPosition, childPosition)).getUid();
Is this comment important?

2020-11-08 19:57 UTC, celinecamacho commented on app/src/main/java/com/github/dedis/student20_pop/utility/attendeeUI/package-info.java
> + * Classes used to display the lhe elements in relation to the attendee UI.
There is a typo between "the" and "elements"

2020-11-08 19:57 UTC, celinecamacho commented on app/src/main/res/layout/fragment_organizer_poll.xml
> +                    android:ems="10"
The 10 value should be stored in the file res/values/dimens.xml, same thing for line 79, 105 and 115

2020-11-08 19:57 UTC, celinecamacho commented on app/src/androidTest/java/com/github/dedis/student20_pop/MainActivityTest.java
> +    //These tests only pass when testingAttendee is true in MainActivity
You can create a function in MainActivity to set testingAttendee to true at the beginning of each test

2020-11-09 22:13 UTC, celinecamacho approved these changes

2020-11-10 10:51 UTC, merged