[be2-scala] Parser implementation with new Json protocol
dedis/student20_pop pull request #83
Opened 2020-11-24 02:15 UTC by RaulinN

Closes #69

2020-11-24 08:43 UTC, SFulpius commented
I added the LAO creation messages, so we can test the code. I will adapt the test so they compile and it should be good.

2020-11-24 10:12 UTC, SFulpius requested changes
Great job! Parsing three levels of Json was not an easy task!
There are a few minor mistakes, please look at my comments

2020-11-24 15:07 UTC, RaulinN commented on src/main/scala/ch/epfl/pop/json/JsonAnswerServer.scala
> +  def sendAnswer(answer: String): Unit = {
I am still not sure how to handle errors. This function only prints them to the terminal as a placeholder

2020-11-24 15:09 UTC, RaulinN commented on src/main/scala/ch/epfl/pop/json/JsonAnswerServer.scala
> +    type ErrorCodes = Value
`Value` represents the type of the enumeration. It comes from the [`Enumeration` abstract class](https://www.scala-lang.org/api/current/scala/Enumeration.html)

2020-11-24 16:08 UTC, RaulinN commented
> Actually `PropagateMessageServer` is a server message, so I don't see why it would make a problem. Also, I dont understand your problem with `id`. For me, it should work without problem. Is it a problem with the parser?

Interestingly enough, this creates a `java.lang.ExceptionInInitializerError`. I have not found why this doesn't work. Moreover there's one lonely Stackoverflow post only mentioning this exception online which speaks about implicit val orders... But I have triple-checked ten times the order 🤔 . I will look into it again soon to see if there's really no way to make it work

2020-11-24 16:37 UTC, SFulpius commented on src/main/scala/ch/epfl/pop/json/JsonAnswerServer.scala
> +    type ErrorCodes = Value
It does not compile on my computer. Does it works on yours?

2020-11-24 16:47 UTC, SFulpius commented on src/main/scala/ch/epfl/pop/json/JsonAnswerServer.scala
> +    type ErrorCodes = Value
Looks like it was a bug in my code. It compiles now.

2020-11-24 16:50 UTC, SFulpius approved these changes

2020-11-24 17:07 UTC, SFulpius commented
> > Actually `PropagateMessageServer` is a server message, so I don't see why it would make a problem. Also, I dont understand your problem with `id`. For me, it should work without problem. Is it a problem with the parser?
> 
> Interestingly enough, this creates a `java.lang.ExceptionInInitializerError`. I have not found why this doesn't work. Moreover there's one lonely Stackoverflow post only mentioning this exception online which speaks about implicit val orders... But I have triple-checked ten times the order thinking . I will look into it again soon to see if there's really no way to make it work

When do you get this exception? I tried with this code 
```
sealed class JsonMessagePublishClient(
                                       val params: MessageParameters,
                                       val id: Int,
                                       val method: Methods,
                                       val jsonrpc: String = JSON_RPC_VERSION
                                     ) extends JsonMessagePubSubClient
```

and I get no error running the tests.

2020-11-30 09:12 UTC, SFulpius commented
We will not add further features to this PR.
@lhmerino or @haoqianzhang if you have some time before tomorrow's meeting to review this PR, it would be appreciated :smile:

2020-12-04 20:40 UTC, lhmerino approved these changes
Looks good! The code is well documented. There are some TODO comments which I assume will be addressed in a future pull request.

2020-12-05 11:02 UTC, SFulpius commented
Thank you for your review!
You're right, TODO are for future work, as the PR was already long enough.

2020-12-05 11:02 UTC, merged