Organization UI
dedis/student20_pop pull request #95
Opened 2020-11-29 20:22 UTC by imaximumGit

The basic design of the organization UI is implemented and a global store for the app is implemented (redux).

2020-12-03 21:43 UTC, RaulinN requested changes
Great job @imaximumGit ! Everything seems to work well! :D 

ℹ️ I didn't review code related to data storage since it is temporary for now. I will add the persistent storage once this PR gets accepted. I also made sure that your current PR compiles/works with the new storage :)

2020-12-03 21:43 UTC, RaulinN commented on PopApp/Components/Witness.js
> +  <FlatList
Both `data` and `renderItem` attributes must be specified in a `FlatList` according to the [documentation](https://reactnative.dev/docs/flatlist)

2020-12-04 12:21 UTC, RaulinN approved these changes
👍

2020-12-04 21:03 UTC, lhmerino requested changes
Looks good but please add more descriptive comments. For example: Instead of "Manage the Home screen" have it say: "Manages the home screen components: a Welcome string, a LAO connect button, and a launch LAO button." And if possible, the link between components such as "Launch LAO" button is linked to the Launch component.

2020-12-05 21:00 UTC, imaximumGit commented on PopApp/Components/DiscussionEvent.js
> +const QUESTION = [
It is some fictive questions/discussions to show how the discussion event component works.

2020-12-08 17:47 UTC, lhmerino approved these changes

2020-12-08 17:53 UTC, merged